name: oro_moskofidi_test_app
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=3.22.2"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  flutter_localizations:
    sdk: flutter

  # dart
  http: 1.2.2
  intl: 0.19.0
  logger: 2.5.0
  equatable: 2.0.7

  # flutter utils
  flutter_bloc: 8.1.6
  flutter_riverpod: 2.6.1

  #codegen
  freezed_annotation: 2.4.2

  # flutter ui
  go_router: 14.6.2
  
  # platform
  shared_preferences: 2.3.3
  image_gallery_saver: 2.0.3
  cached_network_image: 3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0

  # codegen
  freezed: 2.5.2
  build_runner: 2.4.11

flutter:
  generate: true
  uses-material-design: true
